### ISSUE TITLE
iMessage and FaceTime don't work anymore

### ISSUE THREAD

**Issue by ngntriminh** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#47]
Hello, I don't know if it's on my side or something but my iMessage and FaceTime keep loading and seem to be unusable. I'm using your latest commit. iCloud and Photos work fine, only iMessage and FaceTime have this issue. Previously, they worked just fine.

<img width="1142" alt="Screenshot 2024-09-01 at 15 07 21" src="https://github.com/user-attachments/assets/b9551630-002b-402c-bd0a-e1c72aa4ecf6">

**Comment by ngntriminh** [comment]
I figured it out. It's because the newest Sonoma version is not compatible with the latest version of _AirportItlwm.kext_. I just replaced _AirportItlwm.kext_ with [_itlwm.kext_](https://github.com/OpenIntelWireless/itlwm/releases) and [_HeliPort_](https://github.com/OpenIntelWireless/HeliPort) and it works fine now.

**Comment by PIut02** [comment]
I didn't upgrade to the latest macOS to verify, refer to https://github.com/OpenIntelWireless/itlwm/issues/990#issuecomment-2211764704.
This issue seems to be related to the ethernet connection of en0, but I've tried adding `NullEthernet.kext` to fix this, so it shouldn't be happened.
Maybe you should try resetting the network settings and check if en0 is an ethernet connection, but anyway, thanks for the info you gave, I'll state in the readme if I verify this issue.
