### ISSUE TITLE
Randomly freezes

### ISSUE THREAD

**Issue by LoiNguyen99** [PIut02/ROG-Zephyrus-G14-GA401-Hackintosh#6]
Sorry for creating an issue here, I'm using mac ventura on Zephyrus model 2021. My screen sometimes freezes for about 10 seconds. I don't know if you have encountered the same situation or not, could you please show me how to fix it? Thank you.

**Comment by PIut02** [comment]
This is a known issue, but because I don't have a 2021 machine, I don't know exactly where the problem lies. I'm sorry I can't fix it. Also, because I've been busy recently, I haven't had time to update the supported device models in the readme. If you solve this problem, please feel free to commit a pull request.

**Comment by PIut02** [comment]
@LoiNguyen99 Wait, does this mean that you have successfully installed Ventura on the 2021 model?

**Comment by LoiNguyen99** [comment]
yes
But I'm not using your EFI, do you want to take a look? I whill share mine.

**Comment by PIut02** [comment]
Of course, I would like to know what exactly caused this issue. Thank you very much.

**Comment by LoiNguyen99** [comment]
https://drive.google.com/file/d/1o1_cNZWq1hpUufi6YTfBV58iktUA8H6l/view?usp=sharing
